version: "3.3"
services:
  supertuxserver:
    image: ixonstater/stkserver:latest
    ports:
      - 2757:2757/udp
      - 2759:2759/udp
    volumes:
      - ./server_config.xml:/stk/server_config.xml
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}

  supertuxais:
    image: ixonstater/stkai:latest
    depends_on:
      - supertuxserver