version: "3.3"
services:
  supertuxserver:
    image: supertuxserver
    ports:
      - 2757:2757/udp
      - 2759:2759/udp
    volumes:
      - ./server_config.xml:/stk/server_config.xml
    environment:
      - USERNAME=ixonstater
      - PASSWORD=virus1171995

  supertuxais:
    image: supertuxais
    depends_on:
      - supertuxserver